[package]
edition = "2018"
name = "uuidgen"
version = "0.3.0"

[profile.release]
opt-level = 'z'

[dependencies]
qrcodegen = "1.7.0"
reqwest = {version = "0.11.4", features = ["json", "blocking"]}
serde = {version = "1.0.127", features = ["derive"]}
rand = "0.8.4"
